apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: stuff
  title: stuff
  description: Ansible content from kdwyer-rd/stuff (hello_world, patching_linux, EDA rulebooks)
  annotations:
    github.com/project-slug: kdwyer-rd/stuff
    backstage.io/source-location: url:https://github.com/kdwyer-rd/stuff/tree/main/
  tags:
    - ansible
    - aap
    - playbooks
  links:
    - url: https://github.com/kdwyer-rd/stuff
      title: GitHub Repository
      icon: github
    - url: https://example-aap.apps.rosa.kpkuy-2yi3d-fvi.cspo.p3.openshiftapps.com/#/projects/12/details
      title: AAP Project
spec:
  type: service
  lifecycle: experimental
  owner: group:default/rhdh-admin
